services:

  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    ports:
      - 27018:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Start123
      - MONGO_INITDB_DATABASE=raymaster
      - MONGODB_ROOT_PASSWORD=Start123

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    volumes:
      - minio_storage:/container/vol
    ports:
     - "9001:9000"
     - "9002:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: rvc
      MINIO_ROOT_PASSWORD: Start123
    command: server /container/vol --console-address :9001

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping 
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - rmq_data:/var/lib/rabbitmq/
      - rmq_log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rvc
      RABBITMQ_DEFAULT_PASS: Start123

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    restart: unless-stopped
    environment:
      - cluster.name=opensearch
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    restart: unless-stopped
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"

  web:
    image: raynetpublic.azurecr.io/raynetone/technology-catalog:25.3
    depends_on:
      - mongo
      - minio
      - rabbitmq
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - catalog_license:/app/license
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - BASEURL=http://localhost:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ServiceConfig__MongoConfiguration__ConnectionString=mongodb://mongo
      - ServiceConfig__MongoConfiguration__DatabaseName=raymaster
      - ServiceConfig__MongoConfiguration__UserName=mongoadmin
      - ServiceConfig__MongoConfiguration__Password=Start123
      - ServiceConfig__MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000
      - OpenSearch__Urls=["http://opensearch:9200"]

  worker-recognition:
    image: raynetpublic.azurecr.io/raynetone/technology-catalog-worker:25.3
    depends_on:
      - mongo
      - minio
      - rabbitmq
      - web
    restart: unless-stopped
    volumes:
      - worker1_token:/app/tokens
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - WorkerType=recognition
      - TokenStorage__FilePath=tokens/token.json
      - MongoConfiguration__ConnectionString=mongodb://mongo
      - MongoConfiguration__DatabaseName=raymaster
      - MongoConfiguration__UserName=mongoadmin
      - MongoConfiguration__Password=Start123
      - MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000
      
  worker-other:
    image: raynetpublic.azurecr.io/raynetone/technology-catalog-worker:25.3
    depends_on:
      - mongo
      - minio
      - rabbitmq
      - web
    restart: unless-stopped
    volumes:
      - worker2_token:/app/tokens
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - WorkerType=cleanup applycustomattribute export
      - TokenStorage__FilePath=tokens/token.json
      - MongoConfiguration__ConnectionString=mongodb://mongo
      - MongoConfiguration__DatabaseName=raymaster
      - MongoConfiguration__UserName=mongoadmin
      - MongoConfiguration__Password=Start123
      - MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000
      - Synchronization__AutoSyncJobCronExpression=0 6 * * *
      - Synchronization__CachingJobCronExpression=-
      - Vulnerabilities__CachingJobCronExpression=-

  worker-search:
    image: raynetpublic.azurecr.io/raynetone/technology-catalog-worker:25.3
    depends_on:
      - mongo
      - minio
      - rabbitmq
      - web
    restart: unless-stopped
    volumes:
      - worker3_token:/app/tokens
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - WorkerType=cleanup applycustomattribute export
      - TokenStorage__FilePath=tokens/token.json
      - MongoConfiguration__ConnectionString=mongodb://mongo
      - MongoConfiguration__DatabaseName=raymaster
      - MongoConfiguration__UserName=mongoadmin
      - MongoConfiguration__Password=Start123
      - MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000

volumes:
  db_data:
  db_config:
  worker1_token:
  worker2_token:
  worker3_token:
  rmq_data:
  rmq_log:
  minio_storage:
  catalog_license:
  opensearch_data: