version: "3.7"
services:

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    ports:
      - 27018:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Start123
      - MONGO_INITDB_DATABASE=raymaster
      - MONGODB_ROOT_PASSWORD=Start123

  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    volumes:
      - minio_storage:/container/vol
    ports:
     - "9001:9000"
     - "9002:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: rvc
      MINIO_ROOT_PASSWORD: Start123
    command: server /container/vol --console-address :9001

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping 
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - rmq_data:/var/lib/rabbitmq/
      - rmq_log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rvc
      RABBITMQ_DEFAULT_PASS: Start123

  web:
    image: raynetgmbh/rayventory-catalog:12.6
    depends_on:
      - mongo
      - minio
      - rabbitmq
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - catalog_license:/app/license
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - BASEURL=http://localhost:8080
      - ServiceConfig__MongoConfiguration__ConnectionString=mongodb://mongo
      - ServiceConfig__MongoConfiguration__DatabaseName=raymaster
      - ServiceConfig__MongoConfiguration__UserName=mongoadmin
      - ServiceConfig__MongoConfiguration__Password=Start123
      - ServiceConfig__MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000

  worker-recognition:
    image: raynetgmbh/rayventory-catalog-worker:12.6
    depends_on:
      - mongo
      - minio
      - rabbitmq
      - web
    restart: unless-stopped
    volumes:
      - worker1_token:/app/tokens
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - WorkerType=recognition
      - TokenStorage__FilePath=tokens/token.json
      - MongoConfiguration__ConnectionString=mongodb://mongo
      - MongoConfiguration__DatabaseName=raymaster
      - MongoConfiguration__UserName=mongoadmin
      - MongoConfiguration__Password=Start123
      - MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000
      
  worker-other:
    image: raynetgmbh/rayventory-catalog-worker:12.5
    depends_on:
      - mongo
      - minio
      - rabbitmq
      - web
    restart: unless-stopped
    volumes:
      - worker2_token:/app/tokens
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    environment:
      - WorkerType=cleanup applycustomattribute suggestions export
      - TokenStorage__FilePath=tokens/token.json
      - MongoConfiguration__ConnectionString=mongodb://mongo
      - MongoConfiguration__DatabaseName=raymaster
      - MongoConfiguration__UserName=mongoadmin
      - MongoConfiguration__Password=Start123
      - MongoConfiguration__AuthDatabaseName=admin
      - MessageQueue__HostName=rabbitmq
      - MessageQueue__QueuePrefix=rvc
      - MessageQueue__User=rvc
      - MessageQueue__Password=Start123
      - FileStorage__HostName=minio
      - FileStorage__Bucket=rvc
      - FileStorage__Location=local
      - FileStorage__User=rvc
      - FileStorage__Password=Start123
      - FileStorage__Port=9000

volumes:
  db_data:
  db_config:
  worker1_token:
  worker2_token:
  rmq_data:
  rmq_log:
  minio_storage:
  catalog_license:
